use thiserror::Error;

/// Defines the API for the server generated by tonic.
#[allow(clippy::nursery, clippy::pedantic)]
pub mod api {
    tonic::include_proto!("ibc_attestor");

    pub(crate) const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("ibc_attestor_descriptor");
}

mod attestor;
mod interceptor;
mod middleware;
pub mod server;

pub use interceptor::tracing_interceptor;
pub use middleware::LoggingMiddleware;

/// Errors that can occur during RPC operations.
#[derive(Debug, Error)]
pub enum RpcError {
    /// Error from the Tonic transport layer.
    #[error("TonicError: {0}")]
    TonicError(#[from] tonic::transport::Error),
}
