use thiserror::Error;

/// Defines the API for the server generated by tonic.
#[allow(clippy::nursery, clippy::pedantic)]
pub mod api {
    tonic::include_proto!("ibc_attestor");

    pub(crate) const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("ibc_attestor_descriptor");
}

/// Defines the health check API generated by tonic.
#[allow(clippy::nursery, clippy::pedantic, missing_docs)]
pub mod health_api {
    tonic::include_proto!("grpc.health.v1");

    pub(crate) const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("health_descriptor");
}

mod attestor;
mod health;
/// Health check server implementation
pub mod health_server;
mod interceptor;
mod middleware;
/// Server implementation and assembly
pub mod server;

pub use health::HealthService;
pub use interceptor::tracing_interceptor;
pub use middleware::LoggingMiddleware;

/// Errors that can occur during RPC operations.
#[derive(Debug, Error)]
pub enum RpcError {
    /// Error from the Tonic transport layer.
    #[error("TonicError: {0}")]
    TonicError(#[from] tonic::transport::Error),
}
